### PR TITLE
support wsl2 bridged mode

### PR DESCRIPTION
**Pull request by yejunhuang**
The new version win10 win11 22H2 supports wsl2 bridged mode.
Reference link https://github.com/microsoft/WSL/issues/4150 .
It changes the name of vmSwitch from the default "WSL" to a user-modifiable one.

Set in the SpecialFolder.UserProfile/.wslconfig file as follows:

[wsl2]
networkingMode=bridged
vmSwitch=usermodifiable

### CODE REVIEW

**Review by dorssel — COMMENTED** [review]
Very nice!

All my comments are pedantic nitpicks. I will accept it unchanged if you want me to.
However, I do recommend that you add a SPDX-FileCopyrightText for yourself below the existing ones in `WslDistributions.cs`. Only if you want to, of course!

Thanks very much for your contribution. Nice addition.

**Comment by dorssel** [comment]
@benmcmorran
This seems to use an undocumented WSL feature. Do you know more about it? Is it being used correctly like this?

**Comment by benmcmorran** [comment]
Thanks for the ping. I'll ask around internally.

**Comment by yejunhuang** [comment]
@dorssel
I change the code style as you said.
Thanks very much.

**Comment by dorssel** [comment]
@yejunhuang 
Well done, and thanks again!
I will wait a bit to get feedback from the WSL team, but this will get merged soon.

**Comment by benhillis** [comment]
Using undocumented WSL functionality (bridge mode) is unsupported and may stop working at some point in the future. I strongly suggest not merging this PR as-is.

**Comment by CarinaSchoppe** [comment]
> Using undocumented WSL functionality (bridge mode) is unsupported and may stop worki

how do I activate bridged mode on WSL2?

**Comment by dorssel** [comment]
> > Using undocumented WSL functionality (bridge mode) is unsupported and may stop worki
> 
> how do I activate bridged mode on WSL2?

This is not the place to ask WSL questions. This is a PR for usbipd-win.

**Comment by dorssel** [comment]
> Using undocumented WSL functionality (bridge mode) is unsupported and may stop working at some point in the future. I strongly suggest not merging this PR as-is.

I understand that you cannot/will not advertise undocumented features.

However, in this case the undocumented feature is already being used in the wild. One possible response from `usbipd-win` could be: don't do that. But fact is, people do, and it breaks the current `wsl` convenience commands of `usbipd-win`.

This PR does *not* change existing, documented functionality. If users aren't using the undocumented feature, then this PR makes no difference. If they do use it, then currently `usbipd wsl` isn't working for them. So, at worst, this PR may not help in an otherwise already not-functioning "out-of-spec" situation. At best, it makes "out-of-spec" situations that are now not working with `usbipd-win` magically work again.

I am considering displaying a warning if this feature is detected. That will be a different PR.

Merging this one...

**Pull request merged**
