### PR TITLE
Fix unlink race condition

### LINKED ISSUE #538: Connection drop
We are observing connection drops during data transfer via FDTI Serial Converter (VID: 0403 PID: 6001).
The device is passed-through using `usbipd-win version 2.4.1+1.Branch.master.Sha.90acf9456020ca8c6310ca62a71ee23cb6ca34ad` on a Windows 10 Professional system into a WSL2 Ubuntu 20.04 distro.

Logs from `usbipd server`:
```
      Flushing
trce: Usbipd.AttachedClient[1001]
      Unlinking 232631, pending = True, pending count = 2
trce: Usbipd.AttachedClient[1001]
      Aborting endpoint 129
dbug: Usbipd.AttachedClient[1000]
      USBSUP_XFER_STALL -> EPIPE -> -32
dbug: Usbipd.AttachedClient[1000]
      USBSUP_XFER_STALL -> EPIPE -> -32
trce: Usbipd.AttachedClient[1001]
      Unlinking 233577, pending = True, pending count = 2
trce: Usbipd.AttachedClient[1001]
      Aborting endpoint 129
dbug: Usbipd.AttachedClient[1000]
      USBSUP_XFER_STALL -> EPIPE -> -32
dbug: Usbipd.AttachedClient[1000]
      USBSUP_XFER_STALL -> EPIPE -> -32
dbug: Usbipd.PcapNg[1000]
      Flushing
trce: Usbipd.AttachedClient[1001]
      Unlinking 233589, pending = True, pending count = 2
trce: Usbipd.AttachedClient[1001]
      Aborting endpoint 129
dbug: Usbipd.AttachedClient[1000]
      USBSUP_XFER_STALL -> EPIPE -> -32
trce: Usbipd.AttachedClient[1001]
      Unlinking 233590, pending = False, pending count = 0
dbug: Usbipd.AttachedClient[1000]
      USBSUP_XFER_STALL -> EPIPE -> -32
info: Usbipd.ConnectedClient[2]
      Client 172.19.242.161 released device at 1-6 (USB\VID_0403&PID_6001\A7040OCA).
dbug: Usbipd.ConnectedClient[1000]
      Unbind or unplug while attached
dbug: Usbipd.Server[1000]
      connection close: Attempted to read past the end of the stream.
dbug: Usbipd.Server[1000]
      connection closed
dbug: Usbipd.PcapNg[1000]
      Flushing
```

Pcapng file is attached
[usbipd.pcapng.zip](https://github.com/dorssel/usbipd-win/files/10705097/usbipd.pcapng.zip)

### PR DESCRIPTION
**Pull request by dorssel**
Fixes #538

### CODE REVIEW

**Comment by kaplan2539** [comment]
OK, I've tested the latest build. Again, I am not able to re-produce connection drops with the CP2101 adapter.
I see a lot of
```
[ 1323.112492] cp210x ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 1323.112505] vhci_hcd: unlink->seqnum 151555
[ 1323.112506] vhci_hcd: urb->status -104
```
But the USB device remains present in Linux.

However, with the FTDI device I see the connection dropping after 2 seconds:
```
[ 1458.985696] WSL2: Performing memory compaction.
[ 1470.482354] init: (1) WARNING: /etc/resolv.conf updating disabled in /etc/wsl.conf
[ 1472.271725] vhci_hcd vhci_hcd.0: pdev(0) rhport(0) sockfd(3)
[ 1472.271734] vhci_hcd vhci_hcd.0: devid(131076) speed(2) speed_str(full-speed)
[ 1472.271819] vhci_hcd vhci_hcd.0: Device attached
[ 1472.549350] vhci_hcd: vhci_device speed not set
[ 1472.619299] usb 1-1: new full-speed USB device number 5 using vhci_hcd
[ 1472.699142] vhci_hcd: vhci_device speed not set
[ 1472.769135] usb 1-1: SetAddress Request (5) to port 0
[ 1472.810706] usb 1-1: New USB device found, idVendor=0403, idProduct=6001, bcdDevice= 6.00
[ 1472.810710] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1472.810711] usb 1-1: Product: FT232R USB UART
[ 1472.810712] usb 1-1: Manufacturer: FTDI
[ 1472.810712] usb 1-1: SerialNumber: A50285BI
[ 1472.814567] ftdi_sio 1-1:1.0: FTDI USB Serial Device converter detected
[ 1472.814598] usb 1-1: Detected FT232RL
[ 1472.815722] usb 1-1: FTDI USB Serial Device converter now attached to ttyUSB0
[ 1499.422962] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 1499.422969] vhci_hcd: unlink->seqnum 170638
[ 1499.422970] vhci_hcd: urb->status -104
...
[ 1501.593734] vhci_hcd: unlink->seqnum 179196
[ 1501.593734] vhci_hcd: urb->status -104
[ 1501.596954] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 1501.596957] vhci_hcd: unlink->seqnum 179210
[ 1501.596958] vhci_hcd: urb->status -104
[ 1501.601118] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 1501.601126] vhci_hcd: unlink->seqnum 179225
[ 1501.601127] vhci_hcd: urb->status -104
[ 1501.604572] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 1501.604577] vhci_hcd: unlink->seqnum 179239
[ 1501.604578] vhci_hcd: urb->status -104
[ 1501.608067] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 1501.608072] vhci_hcd: unlink->seqnum 179253
[ 1501.608073] vhci_hcd: urb->status -104
[ 1501.611544] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 1501.611550] vhci_hcd: unlink->seqnum 179267
[ 1501.611550] vhci_hcd: urb->status -104
[ 1501.614736] vhci_hcd: unlink->seqnum 179281
[ 1501.614737] vhci_hcd: urb->status 0
[ 1501.614751] vhci_hcd: cannot find a urb of seqnum 179272 max seqnum 179281
[ 1501.614800] vhci_hcd: sendmsg failed!, ret=-32 for 48
[ 1501.614829] vhci_hcd: stop threads
[ 1501.614832] vhci_hcd: release socket
[ 1501.614847] vhci_hcd: disconnect device
[ 1501.614867] usb 1-1: USB disconnect, device number 5
[ 1501.614982] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[ 1501.614989] ftdi_sio 1-1:1.0: device disconnected
[ 1519.993146] WSL2: Performing memory compaction.
[ 1641.007087] WSL2: Performing memory compaction.
```

**Comment by dorssel** [comment]
> [ 1501.601126] vhci_hcd: unlink->seqnum 179225
> [ 1501.601127] vhci_hcd: urb->status -104

These are normal, benign, informational messages. In fact, they have been removed from the Linux kernel since 5.15 or so.
See https://elixir.bootlin.com/linux/v5.14.21/source/drivers/usb/usbip/vhci_hcd.c#L1006 vs https://elixir.bootlin.com/linux/v5.15/source/drivers/usb/usbip/vhci_hcd.c#L969.

It literally means: I asked to cancel the URB (due to the close()), and it worked.

Normally, for read pipes, there are two outstanding requests (such that when one buffer is being returned, the other can already be filled without waiting). This means 2 URBs need to be canceled like this. However, Windows can only cancel *all* URBs on an endpoint, not individual ones. So the main difference is: on bare Linux you will get two successful UNLINK. On Windows you will get one successful UNLINK and the second URB actually completes with EPIPE. This is (or should be), however, perfectly fine. There is always a race condition for asynchronous IO between actual completion (successful or with error) and cancelation. Judging from the USBIP docs (and the examples given there), I *think* I am doing the right thing now (and before this PR it was definitely wrong).

> [ 1501.601118] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32

This is EPIPE for the second outstanding URB. You will not see this on bare Linux, as that would actually UNLINK it like the first. Nevertheless, this is perfectly normal.

We'll see with the FTDI device where my thinking is wrong...

**Comment by dorssel** [comment]
For the history books: latest addition also fixes the order of the replies, when SUBMIT wins (completes) and UNLINK therefore sends a "I can no cancel the URB since it already completed". Previously, the order of these replies could be reversed, which confuses Linux.

**Comment by kaplan2539** [comment]
I've just un-installed usbipd-win, installed the `.msi` from this PR build, and tested:
```
PS C:\> usbipd --version
3.1.1-PullRequest0684.26+Branch.pull-684-merge.Sha.643a89654a1b4843b96601110098343dec72ec76
```

I've tested with the CP2101 device I have - everything still seems to be stable when running `break.py`.

However, with both FTDI devices I have I still see the connection dropping when I run `break.py`:
```
[  898.004039] vhci_hcd: unlink->seqnum 137985
[  898.004039] vhci_hcd: urb->status -104
[  898.007087] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[  898.007090] vhci_hcd: unlink->seqnum 137999
[  898.007091] vhci_hcd: urb->status -104
[  898.010214] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[  898.010220] vhci_hcd: unlink->seqnum 138013
[  898.010221] vhci_hcd: urb->status -104
[  898.013558] vhci_hcd: unlink->seqnum 138027
[  898.013559] vhci_hcd: urb->status 0
[  898.013570] vhci_hcd: cannot find a urb of seqnum 138018 max seqnum 138027
[  898.013602] vhci_hcd: sendmsg failed!, ret=-32 for 48
[  898.013633] vhci_hcd: stop threads
[  898.013635] vhci_hcd: release socket
[  898.013664] vhci_hcd: disconnect device
[  898.013688] usb 1-1: enqueue for inactive port 0
[  898.013691] usb 1-1: enqueue for inactive port 0
[  898.013692] ftdi_sio ttyUSB0: ftdi_set_termios FAILED to set databits/stopbits/parity
[  898.013693] usb 1-1: enqueue for inactive port 0
[  898.013694] ftdi_sio ttyUSB0: ftdi_set_termios urb failed to set baudrate
[  898.013695] usb 1-1: USB disconnect, device number 4
[  898.013695] ftdi_sio ttyUSB0: failed to set flow control: -19
[  898.013787] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[  898.013793] ftdi_sio 1-1:1.0: device disconnected
```

I see this on two FTDI devices of different origin. One is USB-UART converter, and I don't have anything connected to it.
The other FTDI device is streaming data from an accelerometer while I run the `break.py`.

**Pull request merged**
