### PR TITLE
Refactor attach

### LINKED ISSUE #91: Mass storage devices not safely closed on Windows
Using `usbipd wsl attach` produces an error upon mounting in Linux:

> The disk contains an unclean file system (0, 1).
> The file system wasn't safely closed on Windows. Fixing.

It seems the hardware is not safely removed under Windows but virtually just "plugged out".
It may be a source for file system errors.

**Tested on:**
Microsoft Windows [Version 10.0.22000.346]
WSL Ubuntu 5.10.74.3-microsoft-standard-WSL2+

### LINKED ISSUE #152: Regression 1.2.0 -> 1.3.0: Devices that doesn't support disabling can no longer be attached (CM_Disable_DevNode returned CR_NOT_DISABLEABLE)
## Logs

```
$ usbipd wsl attach --busid 6-2
[sudo] password for yusuf:
usbip: error: Attach Request for 6-2 failed - Request Failed

usbipd: error: Failed to attach device with ID '6-2'.
```
```
$ usbipd server
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Yusuf
fail: UsbIpServer.ConnectedClient[3]
      An exception occurred while communicating with the client:
      UsbIpServer.ConfigurationManagerException (1003): CM_Disable_DevNode returned CR_NOT_DISABLEABLE
         at UsbIpServer.ConfigurationManager.ThrowOnError(CONFIGRET configRet, String function) in D:\a\usbipd-win\usbipd-win\UsbIpServer\ConfigurationManager.cs:line 42
         at UsbIpServer.ConfigurationManager.TemporarilyDisabledDevice..ctor(UInt32 deviceNode) in D:\a\usbipd-win\usbipd-win\UsbIpServer\ConfigurationManager.cs:line 323
         at UsbIpServer.ConfigurationManager.TemporarilyDisabledDevice..ctor(String instanceId) in D:\a\usbipd-win\usbipd-win\UsbIpServer\ConfigurationManager.cs:line 316
         at UsbIpServer.ConnectedClient.HandleRequestImportAsync(CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\ConnectedClient.cs:line 136
```

## USB Device Information
| Friendly Name              | Hardware ID                          |
|----------------------------|--------------------------------------|
| Yubico Yubikey 5 NFC       | USB\VID_1050&PID_0407&REV_0543&MI_02 |

## System Information
Microsoft Windows 11 Education 21H2 (Build 22000.348)
Ubuntu 20.04.3 LTS on Windows 10 x86_64 (Kernel 5.10.60.1-microsoft-standard-WSL2)
Windows Subsystem for Linux Preview from Microsoft Store

## Context
It was working fine with v1.2.0, it got broken with v1.3.0. It might be related to #134.

### LINKED ISSUE #155: Regression 1.2.0 -> 1.3.0: Unplugging USB mass storage in WSL leads to crash
MS Windows 11 x64 [Version 10.0.22000.348]
WSL v2 Ubuntu-CommPrev Linux 5.10.74.3-microsoft-standard-WSL2+
**usbipd-win 1.3.0**

Unplugging a USB mass storage after unmounting it in WSL2 (but not detaching with usbipd) leads to crash:
`Fatal error while logging another fatal error.`
Windows doesn't realize that this device was unplugged. 
Plugging in the device again does not cause any reaction on Windows. After restarting usbipd it is still attached there.

see: #153 
Trace: [log2.txt](https://github.com/dorssel/usbipd-win/files/7677870/log2.txt)

### PR DESCRIPTION
**Pull request by dorssel**
- Use restart instead of disable/enable
- Fix unplug detect
- Fix cleanup on startup for non-present devices

Fixes #152 
Fixed #155 
Resolves #91

### CODE REVIEW

**Comment by dorssel** [comment]
@shanselman 
Version 1.3.0 contains the fix that resolved your earlier issue with attach. Unfortunately, it introduced a regression bug, see #152.

This PR tries to resolve the regression, of course at the risk of a regression with your original problem. Could you please test the build artifact from this PR? It is at https://github.com/dorssel/usbipd-win/actions/runs/1554111229. Thanks!

**Comment by akuropka** [comment]
@dorssel,
it did work with two out of three USB medias.

The non-working one can be seen as device inside WSL:
> NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
> sda    8:0    0 344,9M  1 disk
> sdb    8:16   0     4G  0 disk [SWAP]
> sdc    8:32   0   256G  0 disk /
> sdd    8:48   1  29,7G  0 disk
Yet there are no partitions available. (`fdisk: cannot open /dev/sdd: Input/output error`).
Trace: [log1.txt](https://github.com/dorssel/usbipd-win/files/7677879/log1.txt)

However, with the working ones I experienced if I unmount the media and unplug it (without detaching through usbipd-win) the service crashes (`Fatal error while logging another fatal error.)`).
You'll find the trace attached: [log2.txt](https://github.com/dorssel/usbipd-win/files/7677870/log2.txt)
This definitely didn't happen before.

**Comment by dorssel** [comment]
@akuropka 
For the first device, the error is:

> USBSUP_XFER_UNDERRUN -> EREMOTEIO -> -121
> ...
> USBSUP_XFER_STALL -> EPIPE -> -32

Please file a new issue for this; the problem is unrelated (and new!).
The other error is:

> Fatal error while logging another fatal error.

That, too, is a new error and may be a regression bug, but  a different one then this. Could you test if this happens with the 1.3.0 release as well and not just with this PR?

**Comment by akuropka** [comment]
Both issues happen with the 1.3.0 release as well.
Sorry for not realizing before due to lack of testing.

**Comment by dorssel** [comment]
@akuropka 
Thanks for testing.
#155 is actually a regression bug, this still worked on 1.2.0.
#154 is unrelated and (I think) has never worked in the past, correct?

**Comment by akuropka** [comment]
#154 should have worked in the past but I will do some further testing tomorrow.
(Actually the device is a memory card reader and it may be a card-specific error.)

**Comment by dorssel** [comment]
@shanselman 
@akuropka 
Newest artifact at https://github.com/dorssel/usbipd-win/actions/runs/1555776340.

**Comment by shanselman** [comment]
Ok I will test later tonight or early in the morning, I'm on a plane. Craig and I are planning on a YouTube video on this project tomorrow so if this doesn't work we will reschedule.

**Comment by akuropka** [comment]
works perfectly regarding #155.

**Comment by shanselman** [comment]
@dorssel works! :shipit:

**Pull request merged**
