### PR TITLE
Add option --hardware-id

### LINKED ISSUE #336: Feature - `attach` devices by specifying `Vendor:Product` pair
# Issue
A device can be attached to any USB port causing the command required to attach to change outside of script control 

# Feature Idea
Provide an option to attach devices(s) via `Product:Vendor` ID instead of `--busid` e.g.
`usbipd wsl attach --product-vendor a1f2:ec5a`

# Benefits
- No longer need to supply bus or device index
- Simplify attach multiple devices of same Product+vendor in the same attach call

### PR DESCRIPTION
**Pull request by dorssel**
Fixes #336

### CODE REVIEW

**Comment by dorssel** [comment]
@CraigHutchinson
Can you test this, please? Installer is here: https://github.com/dorssel/usbipd-win/actions/runs/2163643790

**Comment by CraigHutchinson** [comment]
@dorssel Very nice. My WSL setup prevents the `usbipd wsl attach -i 04d8:ec5a` succeeding now... think its a network/ip issue as my WSL2 box has issues accessing internet now.

Can see this works though  as this feature significantly simplifies the usage.
image

I tested bind also which works perfectly, much more elegant than before:
image

**Comment by CraigHutchinson** [comment]
Some observation we could raise as a new ticket if you prefer is:

1.  that there is no `list` view containing the VID:PID pair? In my case I know them but many users may be using third party devices and digging into Device-Manager to get this or decoding the `state` output is far from an ideal match.
image

2. separate feature would be to support `-n, --name <NAME>  Share device matching pattern<NAME> e.g. "*Camera*"` this would blow the usability to even higher levels. For example "Integrated Camera" from any manufacturer can be mounted 🥇

**Comment by dorssel** [comment]
@CraigHutchinson 
> EDIT: It appears I can attach from inside the WSL2 VM but not from windows - same as https://github.com/dorssel/usbipd-win/issues/335

Can you check the firewall rule that was created? It should point to the EXE at `C:\Program Files\usbipd-win\usbipd.exe`. What IP address are you using to attach from within WSL2? Does it work if you use the WSL switch address?

**Comment by dorssel** [comment]
@CraigHutchinson 
> that there is no list view containing the VID:PID pair?

It makes sense to add it there, as well as to the PowerShell module metadata.

**Comment by CraigHutchinson** [comment]
Frans van Dorsselaer Thursday, 14 April, 22:20
Can you check the firewall rule that was created? It should point to the EXE at C:\\Program Files\\usbipd-win\\usbipd.exe. What IP address are you using to attach from within WSL2? Does it work if you use the WSL switch address?
I will be back in the office Tuesday and will investigate. From the Wsl client I can attach when I use local WiFi ip of the host I.e 192.168.1.100 and if I recall using the wsl switch address 172.x.x.x didn't work when I last tried. There were some issues when i first migrated to WSL2 with Internet access, likely related. I don't expect this is anything relevant to usbip though and just system configuration for now.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dorssel** [comment]
@CraigHutchinson 
New version, shows VID:PID in the lists. Can you give it another try?
https://github.com/dorssel/usbipd-win/actions/runs/2176164339

**Comment by CraigHutchinson** [comment]
> @CraigHutchinson New version, shows VID:PID in the lists. Can you give it another try? https://github.com/dorssel/usbipd-win/actions/runs/2176164339

Great. I had to uninstall the previous build as installer saw it as the same version.

Can confirm VID:PID are displayed very nicely so much simplify the features usage (as/when I resolve my WSL 3240 port issues!):
image

**Pull request merged**
