### PR TITLE
Add USB packet capture

### PR DESCRIPTION
**Pull request by dorssel**

### CODE REVIEW

**Comment by vmarrazz** [comment]
Hi @dorssel 
I have found usbipd a powerful tool for my testing activity for a device connected via "USB to serial" converter.

I have some question on this feature/PR:
- Where is possible to find a description of this feature/PR?
- Does it allow to capture messages exchanged without any interference with application running into WSL2?
Regards
Vincenzo

**Comment by dorssel** [comment]
@vmarrazz 
- No description yet. This PR is still in draft and probably not functional. It doesn't even have the latest commits due to lack of time.
- Yes, it eventually will.

For the time being, you can achieve (nearly) the same by using `tcpdump` or `tshark` on `/dev/usbmon` on the Linux side of things, but for WSL that would mean compiling your own kernel with support for `usbmon`.

**Comment by vmarrazz** [comment]
@dorssel thanks for feedback
Do you have a guide to compile kernel specific for WSL2?

Regards

**Comment by dorssel** [comment]
@vmarrazz 
Other than https://github.com/dorssel/usbipd-win/wiki/WSL-support? No. You probably will have to enable some CONFIG_XXX referring to `usbmon`, but I have no clue which one.

**Comment by vmarrazz** [comment]
@dorssel 
Thanks you.
The WSL-support link provide me all necessary information to compile kernel for WSL.
Other information I need was related usbmon capture but Wireshark/tshark has many wiki about it ;-)

Regards

**Pull request merged**
